# Generated by Django 4.0.4 on 2022-05-23 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_amounts', models.CharField(choices=[('1', '1'), ('2', '2'), ('4', '4')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_production_date', models.DateField(default=datetime.date(2022, 5, 23))),
                ('device_serial_number', models.CharField(default=None, max_length=50)),
                ('device_warantee_date', models.DateField(default=datetime.date(2022, 5, 23))),
                ('device_is_working', models.BooleanField(default=True)),
                ('device_special_notes', models.CharField(blank=True, default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(default=None, max_length=50)),
                ('device_serie', models.CharField(default=None, max_length=50)),
                ('device_serie_num', models.IntegerField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device')),
            ],
            bases=('inventory_management.device',),
        ),
        migrations.CreateModel(
            name='Camera_typ',
            fields=[
                ('device_type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device_type')),
            ],
            bases=('inventory_management.device_type',),
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device')),
            ],
            bases=('inventory_management.device',),
        ),
        migrations.CreateModel(
            name='Projector_Brand_Typ',
            fields=[
                ('device_type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device_type')),
            ],
            bases=('inventory_management.device_type',),
        ),
        migrations.CreateModel(
            name='SmartBoard',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device')),
            ],
            bases=('inventory_management.device',),
        ),
        migrations.CreateModel(
            name='SmartBoard_typ',
            fields=[
                ('device_type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device_type')),
            ],
            bases=('inventory_management.device_type',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device')),
            ],
            bases=('inventory_management.device',),
        ),
        migrations.CreateModel(
            name='Speaker_typ',
            fields=[
                ('device_type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory_management.device_type')),
            ],
            bases=('inventory_management.device_type',),
        ),
        migrations.AddField(
            model_name='device',
            name='device_typ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory_management.device_type'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_nr', models.CharField(choices=[('BA1', 'BA1'), ('BA2', 'BA2')], default=1, max_length=10)),
                ('floor_nr', models.CharField(choices=[('BST', 'Basement'), ('GF', 'Ground Floor'), ('1F', 'First Floor'), ('2F', 'Second Floor')], default='basement', max_length=10)),
                ('room_name', models.CharField(max_length=10)),
                ('canva', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.canvas')),
                ('projector', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.projector')),
                ('smartboard', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.smartboard')),
                ('speaker', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.speaker')),
            ],
        ),
    ]
