# Generated by Django 4.0.4 on 2022-05-31 14:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_alter_device_device_production_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_production_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 14, 17, 15, 409385, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_warranty_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 14, 17, 15, 409385, tzinfo=utc)),
        ),
    ]
